esphome:
  name: "water-pressure-01"
  friendly_name: "Water Pressure 01"
  includes:
    - templates/calibration_tables.h

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: !secret pressure_probe_encryption_key

ota:
  - platform: esphome
    password: !secret pressure_probe_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Pressure-01-Fallback"
    password: !secret pressure_probe_wifi_ap_password

captive_portal:

packages:
  probe1: !include
    file: templates/pressure_probe.yaml
    vars:
      probe_id: "1"
      probe_pin: GPIO1
      calibration_id: "0-0.8MPa"
  probe2: !include
    file: templates/pressure_probe.yaml
    vars:
      probe_id: "2"
      probe_pin: GPIO3
      calibration_id: "0-0.8MPa"
